# Build

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: R ${{ matrix.config.r }} | ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-20.04,   r: '4.2.1', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
    
    env:
        INSPIRE_API_ENDPOINT: ${{ secrets.INSPIRE_API_ENDPOINT }}
        INSPIRE_API_KEY: ${{ secrets.INSPIRE_API_KEY }}
    
    steps:
      - uses: actions/checkout@v2
      #R Set-up
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
      #Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            sf
            units
            ncdf4
            jqr
            jsonld
            emld
            EML
      #Check R Package
      - name: Check R package
        uses: r-lib/actions/check-r-package@check-r-package
        with:
          artifact-name: geometa_r-${{ matrix.config.r }}_${{ matrix.config.os }}-results
